### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Destrob0** [Destrob0/homepage#8]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by maksym-strus** [comment]
<h2>Résumé</h2>
<p><strong>I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven</strong></p>

**Comment by Destrob0** [comment]
Thanx)

**Comment by maksym-strus** [comment]
```
<h2>Résumé</h2>
                    <p>
                      &mdash; I do not compete with others, the only competition
                      that challenges me is myself. As a fighter, friend and an
                      employee I am known as contemplative, tortured and driven
                    </p>
```
